[external_core3]
mode = "stdio"
command = "./stormakt-core/SystemRegisIII.ExternalCore.Stormakt3020"
args = ""
working_directory = "."
env = ""
wfex_path = "/tmp/waylandforge-stormakt3020-alpha.wfex"
pointer_driver = "stormakt_rts"
socket_path = "/tmp/waylandforge-stormakt3020-alpha.sock"
protocol_policy = "prefer-v2"
frame_transport = "prefer-shm"
frame_codec = "prefer-packrle"
presentation_mode = "lockstep"
shared_memory_directory = ""
max_frame_width = 8192
max_frame_height = 8192
max_frame_bytes = 268435456
