using System.Globalization;
using SystemRegisIII.WaylandForge.Ui;

namespace SystemRegisIII.Host.WaylandForge;

internal enum UiWindowMode
{
    Tiled,
    Floating,
    Mixed,
}

internal sealed class UiConfig
{
    public UiWindowMode WindowMode { get; set; } = UiWindowMode.Tiled;
    public string Theme { get; set; } = "dark";
    public string Scale { get; set; } = "fit";
    public UiStyleConfig Style { get; } = new();
    public UiTileLayoutConfig Layout { get; } = new();
    public UiExternalCoreConfig ExternalCore { get; } = new();
    public Dictionary<string, UiWindowConfig> Windows { get; } = new(StringComparer.OrdinalIgnoreCase);

    public static UiConfig Load(string defaultsPath, string localPath)
    {
        var config = new UiConfig();
        if (File.Exists(defaultsPath))
        {
            config.Apply(File.ReadAllLines(defaultsPath));
        }
        if (File.Exists(localPath))
        {
            config.Apply(File.ReadAllLines(localPath));
        }
        return config;
    }

    public void Save(string path)
    {
        string? directory = Path.GetDirectoryName(path);
        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        using var writer = new StreamWriter(path);
        writer.WriteLine("# WaylandForge local UI state. Generated by the host.");
        writer.WriteLine();
        writer.WriteLine("[ui]");
        writer.WriteLine($"window_mode = \"{Format(WindowMode)}\"");
        writer.WriteLine($"theme = \"{Theme.ToLowerInvariant()}\"");
        writer.WriteLine($"scale = \"{Scale.ToLowerInvariant()}\"");
        writer.WriteLine($"bling = {Style.Bling.ToString().ToLowerInvariant()}");
        writer.WriteLine($"rainbow_borders = {Style.RainbowBorders.ToString().ToLowerInvariant()}");
        writer.WriteLine($"button_style = \"{Style.ButtonStyle.ToLowerInvariant()}\"");
        writer.WriteLine($"border_effect = \"{Style.BorderEffect.ToLowerInvariant()}\"");
        writer.WriteLine($"effect_speed = {Style.EffectSpeed.ToString(CultureInfo.InvariantCulture)}");
        writer.WriteLine($"effect_strength = {Style.EffectStrength.ToString(CultureInfo.InvariantCulture)}");
        writer.WriteLine($"border_thickness = {Style.BorderThickness.ToString(CultureInfo.InvariantCulture)}");
        writer.WriteLine();
        writer.WriteLine("[ui.layout]");
        writer.WriteLine($"root = \"{Layout.Root}\"");
        writer.WriteLine();
        writer.WriteLine("[external_core]");
        writer.WriteLine($"command = \"{Escape(ExternalCore.Command)}\"");
        writer.WriteLine($"args = \"{Escape(ExternalCore.Args)}\"");
        writer.WriteLine($"working_directory = \"{Escape(ExternalCore.WorkingDirectory)}\"");
        writer.WriteLine();

        foreach (KeyValuePair<string, UiWindowConfig> pair in Windows.OrderBy(static pair => pair.Value.Order).ThenBy(static pair => pair.Key, StringComparer.OrdinalIgnoreCase))
        {
            UiWindowConfig window = pair.Value;
            writer.WriteLine($"[ui.windows.{pair.Key}]");
            writer.WriteLine($"open = {window.Open.ToString().ToLowerInvariant()}");
            writer.WriteLine($"slot = \"{window.Slot}\"");
            writer.WriteLine($"order = {window.Order.ToString(CultureInfo.InvariantCulture)}");
            writer.WriteLine($"x = {window.X.ToString(CultureInfo.InvariantCulture)}");
            writer.WriteLine($"y = {window.Y.ToString(CultureInfo.InvariantCulture)}");
            writer.WriteLine($"width = {window.Width.ToString(CultureInfo.InvariantCulture)}");
            writer.WriteLine($"height = {window.Height.ToString(CultureInfo.InvariantCulture)}");
            writer.WriteLine();
        }
    }

    public UiWindowConfig Window(string key)
    {
        if (!Windows.TryGetValue(key, out UiWindowConfig? window))
        {
            window = new UiWindowConfig { Slot = "floating", Order = Windows.Count * 10 };
            Windows[key] = window;
        }
        return window;
    }

    private void Apply(IEnumerable<string> lines)
    {
        string section = string.Empty;
        foreach (string rawLine in lines)
        {
            string line = StripComment(rawLine).Trim();
            if (line.Length == 0)
            {
                continue;
            }

            if (line.StartsWith('[') && line.EndsWith(']'))
            {
                section = line[1..^1].Trim();
                continue;
            }

            int equals = line.IndexOf('=');
            if (equals <= 0)
            {
                continue;
            }

            string key = line[..equals].Trim();
            string value = Unquote(line[(equals + 1)..].Trim());
            ApplyValue(section, key, value);
        }
    }

    private void ApplyValue(string section, string key, string value)
    {
        if (string.Equals(section, "ui", StringComparison.OrdinalIgnoreCase))
        {
            switch (key.ToLowerInvariant())
            {
                case "window_mode":
                    WindowMode = ParseWindowMode(value, WindowMode);
                    break;
                case "theme":
                    Theme = value;
                    break;
                case "scale":
                    Scale = value;
                    break;
                case "bling":
                    Style.Bling = ParseBool(value, Style.Bling);
                    break;
                case "rainbow_borders":
                    Style.RainbowBorders = ParseBool(value, Style.RainbowBorders);
                    break;
                case "button_style":
                    Style.ButtonStyle = ParseButtonStyle(value, Style.ButtonStyle);
                    break;
                case "border_effect":
                    Style.BorderEffect = ParseBorderEffect(value, Style.BorderEffect);
                    break;
                case "effect_speed":
                    Style.EffectSpeed = Math.Clamp(ParseInt(value, Style.EffectSpeed), 1, 4);
                    break;
                case "effect_strength":
                    Style.EffectStrength = Math.Clamp(ParseInt(value, Style.EffectStrength), 1, 4);
                    break;
                case "border_thickness":
                    Style.BorderThickness = Math.Clamp(ParseInt(value, Style.BorderThickness), 1, 4);
                    break;
            }
            return;
        }

        if (string.Equals(section, "ui.layout", StringComparison.OrdinalIgnoreCase))
        {
            if (string.Equals(key, "root", StringComparison.OrdinalIgnoreCase))
            {
                Layout.Root = value;
            }
            return;
        }

        if (string.Equals(section, "external_core", StringComparison.OrdinalIgnoreCase))
        {
            switch (key.ToLowerInvariant())
            {
                case "command":
                    ExternalCore.Command = value;
                    break;
                case "args":
                    ExternalCore.Args = value;
                    break;
                case "working_directory":
                    ExternalCore.WorkingDirectory = value;
                    break;
            }
            return;
        }

        const string windowPrefix = "ui.windows.";
        if (!section.StartsWith(windowPrefix, StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        string windowKey = section[windowPrefix.Length..];
        UiWindowConfig window = Window(windowKey);
        switch (key.ToLowerInvariant())
        {
            case "open":
                window.Open = bool.TryParse(value, out bool open) && open;
                break;
            case "slot":
                window.Slot = value;
                break;
            case "order":
                window.Order = ParseInt(value, window.Order);
                break;
            case "x":
                window.X = ParseInt(value, window.X);
                break;
            case "y":
                window.Y = ParseInt(value, window.Y);
                break;
            case "width":
                window.Width = ParseInt(value, window.Width);
                break;
            case "height":
                window.Height = ParseInt(value, window.Height);
                break;
        }
    }

    private static UiWindowMode ParseWindowMode(string value, UiWindowMode fallback) => value.Trim().ToLowerInvariant() switch
    {
        "floating" => UiWindowMode.Floating,
        "mixed" => UiWindowMode.Mixed,
        "tiled" => UiWindowMode.Tiled,
        _ => fallback,
    };

    private static string Format(UiWindowMode mode) => mode switch
    {
        UiWindowMode.Floating => "floating",
        UiWindowMode.Mixed => "mixed",
        _ => "tiled",
    };

    private static int ParseInt(string value, int fallback)
    {
        return int.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out int parsed) ? parsed : fallback;
    }

    private static bool ParseBool(string value, bool fallback)
    {
        return bool.TryParse(value, out bool parsed) ? parsed : fallback;
    }

    private static string ParseButtonStyle(string value, string fallback)
    {
        return value.Trim().ToLowerInvariant() switch
        {
            "flat" => "flat",
            "edge" => "edge",
            "loud" => "loud",
            _ => fallback,
        };
    }

    private static string ParseBorderEffect(string value, string fallback)
    {
        return value.Trim().ToLowerInvariant() switch
        {
            "still" => "still",
            "glow" => "glow",
            "flow" => "flow",
            _ => fallback,
        };
    }

    private static string StripComment(string line)
    {
        bool inString = false;
        for (int i = 0; i < line.Length; i++)
        {
            if (line[i] == '"')
            {
                inString = !inString;
            }
            else if (!inString && line[i] == '#')
            {
                return line[..i];
            }
        }
        return line;
    }

    private static string Unquote(string value)
    {
        value = value.Trim();
        return value.Length >= 2 && value[0] == '"' && value[^1] == '"' ? value[1..^1] : value;
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
    }
}

internal sealed class UiWindowConfig
{
    public bool Open { get; set; }
    public string Slot { get; set; } = "floating";
    public int Order { get; set; }
    public int X { get; set; }
    public int Y { get; set; }
    public int Width { get; set; }
    public int Height { get; set; }

    public bool HasRect => Width > 0 && Height > 0;

    public RectI ToRect()
    {
        return new RectI(X, Y, Width, Height);
    }

    public void FromWindow(UiWindowState state)
    {
        Open = state.IsOpen;
        if (state.Rect is RectI rect)
        {
            X = rect.X;
            Y = rect.Y;
            Width = rect.Width;
            Height = rect.Height;
        }
    }
}

internal sealed class UiStyleConfig
{
    public bool Bling { get; set; }
    public bool RainbowBorders { get; set; } = true;
    public string ButtonStyle { get; set; } = "flat";
    public string BorderEffect { get; set; } = "glow";
    public int EffectSpeed { get; set; } = 1;
    public int EffectStrength { get; set; } = 1;
    public int BorderThickness { get; set; } = 1;
}

internal sealed class UiTileLayoutConfig
{
    public string Root { get; set; } = string.Empty;
}

internal sealed class UiExternalCoreConfig
{
    public string Command { get; set; } = string.Empty;
    public string Args { get; set; } = string.Empty;
    public string WorkingDirectory { get; set; } = string.Empty;
}
