using System.Globalization;
using SystemRegisIII.Core;
using SystemRegisIII.WaylandForge.Ui;

namespace SystemRegisIII.Host.WaylandForge;

internal enum UiWindowMode
{
    Tiled,
    Floating,
    Mixed,
}

internal sealed class UiConfig
{
    public UiWindowMode WindowMode { get; set; } = UiWindowMode.Tiled;
    public string Theme { get; set; } = "dark";
    public string Scale { get; set; } = "fit";
    public UiStyleConfig Style { get; } = new();
    public UiAudioConfig Audio { get; } = new();
    public UiSaturnConfig Saturn { get; } = new();
    public UiInputConfig Input { get; } = new();
    public Dictionary<string, UiInputConfig> CoreInputs { get; } = new(StringComparer.OrdinalIgnoreCase);
    public UiTileLayoutConfig Layout { get; } = new();
    public UiExternalCoreConfig ExternalCore { get; } = new();
    public UiExternalCoreConfig ExternalCore2 { get; } = new();
    public UiExternalCoreConfig ExternalCore3 { get; } = new();
    public Dictionary<string, UiWindowConfig> Windows { get; } = new(StringComparer.OrdinalIgnoreCase);

    public static UiConfig Load(string defaultsPath, string localPath)
    {
        var config = new UiConfig();
        if (File.Exists(defaultsPath))
        {
            config.Apply(File.ReadAllLines(defaultsPath));
        }
        if (File.Exists(localPath))
        {
            config.Apply(File.ReadAllLines(localPath));
        }
        return config;
    }

    public void Save(string path)
    {
        string? directory = Path.GetDirectoryName(path);
        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        using var writer = new StreamWriter(path);
        writer.WriteLine("# WaylandForge local UI state. Generated by the host.");
        writer.WriteLine();
        writer.WriteLine("[ui]");
        writer.WriteLine($"window_mode = \"{Format(WindowMode)}\"");
        writer.WriteLine($"theme = \"{Theme.ToLowerInvariant()}\"");
        writer.WriteLine($"scale = \"{Scale.ToLowerInvariant()}\"");
        writer.WriteLine($"bling = {Style.Bling.ToString().ToLowerInvariant()}");
        writer.WriteLine($"rainbow_borders = {Style.RainbowBorders.ToString().ToLowerInvariant()}");
        writer.WriteLine($"button_style = \"{Style.ButtonStyle.ToLowerInvariant()}\"");
        writer.WriteLine($"border_effect = \"{Style.BorderEffect.ToLowerInvariant()}\"");
        writer.WriteLine($"effect_speed = {Style.EffectSpeed.ToString(CultureInfo.InvariantCulture)}");
        writer.WriteLine($"effect_strength = {Style.EffectStrength.ToString(CultureInfo.InvariantCulture)}");
        writer.WriteLine($"border_thickness = {Style.BorderThickness.ToString(CultureInfo.InvariantCulture)}");
        writer.WriteLine();
        writer.WriteLine("[audio]");
        writer.WriteLine($"volume = {Audio.Volume.ToString(CultureInfo.InvariantCulture)}");
        writer.WriteLine();
        writer.WriteLine("[saturn]");
        writer.WriteLine($"last_disc = \"{Escape(Saturn.LastDisc)}\"");
        writer.WriteLine();
        writer.WriteLine("[input]");
        foreach (KeyValuePair<string, string> pair in Input.Bindings.OrderBy(static pair => pair.Key, StringComparer.OrdinalIgnoreCase))
        {
            writer.WriteLine($"{pair.Key} = \"{Escape(pair.Value)}\"");
        }
        writer.WriteLine();
        writer.WriteLine("[controller]");
        foreach (KeyValuePair<string, string> pair in Input.ControllerBindings.OrderBy(static pair => pair.Key, StringComparer.OrdinalIgnoreCase))
        {
            writer.WriteLine($"{pair.Key} = \"{Escape(pair.Value)}\"");
        }
        writer.WriteLine();
        foreach (KeyValuePair<string, UiInputConfig> profile in CoreInputs.OrderBy(static pair => pair.Key, StringComparer.OrdinalIgnoreCase))
        {
            writer.WriteLine($"[input.{profile.Key}]");
            foreach (KeyValuePair<string, string> pair in profile.Value.Bindings.OrderBy(static pair => pair.Key, StringComparer.OrdinalIgnoreCase))
            {
                writer.WriteLine($"{pair.Key} = \"{Escape(pair.Value)}\"");
            }
            writer.WriteLine();
            writer.WriteLine($"[controller.{profile.Key}]");
            foreach (KeyValuePair<string, string> pair in profile.Value.ControllerBindings.OrderBy(static pair => pair.Key, StringComparer.OrdinalIgnoreCase))
            {
                writer.WriteLine($"{pair.Key} = \"{Escape(pair.Value)}\"");
            }
            writer.WriteLine();
        }
        writer.WriteLine("[ui.layout]");
        writer.WriteLine($"root = \"{Layout.Root}\"");
        writer.WriteLine();
        writer.WriteLine("[external_core]");
        writer.WriteLine($"mode = \"{Escape(ExternalCore.Mode)}\"");
        writer.WriteLine($"command = \"{Escape(ExternalCore.Command)}\"");
        writer.WriteLine($"args = \"{Escape(ExternalCore.Args)}\"");
        writer.WriteLine($"working_directory = \"{Escape(ExternalCore.WorkingDirectory)}\"");
        writer.WriteLine($"env = \"{Escape(ExternalCore.Env)}\"");
        writer.WriteLine($"wfex_path = \"{Escape(ExternalCore.WfexPath)}\"");
        writer.WriteLine($"pointer_driver = \"{Escape(ExternalCore.PointerDriver)}\"");
        writer.WriteLine($"socket_path = \"{Escape(ExternalCore.SocketPath)}\"");
        WriteWfexLimits(writer, ExternalCore);
        writer.WriteLine();
        writer.WriteLine("[external_core2]");
        writer.WriteLine($"mode = \"{Escape(ExternalCore2.Mode)}\"");
        writer.WriteLine($"command = \"{Escape(ExternalCore2.Command)}\"");
        writer.WriteLine($"args = \"{Escape(ExternalCore2.Args)}\"");
        writer.WriteLine($"working_directory = \"{Escape(ExternalCore2.WorkingDirectory)}\"");
        writer.WriteLine($"env = \"{Escape(ExternalCore2.Env)}\"");
        writer.WriteLine($"wfex_path = \"{Escape(ExternalCore2.WfexPath)}\"");
        writer.WriteLine($"pointer_driver = \"{Escape(ExternalCore2.PointerDriver)}\"");
        writer.WriteLine($"socket_path = \"{Escape(ExternalCore2.SocketPath)}\"");
        WriteWfexLimits(writer, ExternalCore2);
        writer.WriteLine();
        writer.WriteLine("[external_core3]");
        writer.WriteLine($"mode = \"{Escape(ExternalCore3.Mode)}\"");
        writer.WriteLine($"command = \"{Escape(ExternalCore3.Command)}\"");
        writer.WriteLine($"args = \"{Escape(ExternalCore3.Args)}\"");
        writer.WriteLine($"working_directory = \"{Escape(ExternalCore3.WorkingDirectory)}\"");
        writer.WriteLine($"env = \"{Escape(ExternalCore3.Env)}\"");
        writer.WriteLine($"wfex_path = \"{Escape(ExternalCore3.WfexPath)}\"");
        writer.WriteLine($"pointer_driver = \"{Escape(ExternalCore3.PointerDriver)}\"");
        writer.WriteLine($"socket_path = \"{Escape(ExternalCore3.SocketPath)}\"");
        WriteWfexLimits(writer, ExternalCore3);
        writer.WriteLine();

        foreach (KeyValuePair<string, UiWindowConfig> pair in Windows.OrderBy(static pair => pair.Value.Order).ThenBy(static pair => pair.Key, StringComparer.OrdinalIgnoreCase))
        {
            UiWindowConfig window = pair.Value;
            writer.WriteLine($"[ui.windows.{pair.Key}]");
            writer.WriteLine($"open = {window.Open.ToString().ToLowerInvariant()}");
            writer.WriteLine($"slot = \"{window.Slot}\"");
            writer.WriteLine($"order = {window.Order.ToString(CultureInfo.InvariantCulture)}");
            writer.WriteLine($"x = {window.X.ToString(CultureInfo.InvariantCulture)}");
            writer.WriteLine($"y = {window.Y.ToString(CultureInfo.InvariantCulture)}");
            writer.WriteLine($"width = {window.Width.ToString(CultureInfo.InvariantCulture)}");
            writer.WriteLine($"height = {window.Height.ToString(CultureInfo.InvariantCulture)}");
            writer.WriteLine();
        }
    }

    public UiWindowConfig Window(string key)
    {
        if (!Windows.TryGetValue(key, out UiWindowConfig? window))
        {
            window = new UiWindowConfig { Slot = "floating", Order = Windows.Count * 10 };
            Windows[key] = window;
        }
        return window;
    }

    public UiInputConfig CoreInput(string key)
    {
        if (!CoreInputs.TryGetValue(key, out UiInputConfig? input))
        {
            input = new UiInputConfig(withDefaults: false);
            CoreInputs[key] = input;
        }
        return input;
    }

    private void Apply(IEnumerable<string> lines)
    {
        string section = string.Empty;
        foreach (string rawLine in lines)
        {
            string line = StripComment(rawLine).Trim();
            if (line.Length == 0)
            {
                continue;
            }

            if (line.StartsWith('[') && line.EndsWith(']'))
            {
                section = line[1..^1].Trim();
                continue;
            }

            int equals = line.IndexOf('=');
            if (equals <= 0)
            {
                continue;
            }

            string key = line[..equals].Trim();
            string value = Unquote(line[(equals + 1)..].Trim());
            ApplyValue(section, key, value);
        }
    }

    private void ApplyValue(string section, string key, string value)
    {
        if (string.Equals(section, "ui", StringComparison.OrdinalIgnoreCase))
        {
            switch (key.ToLowerInvariant())
            {
                case "window_mode":
                    WindowMode = ParseWindowMode(value, WindowMode);
                    break;
                case "theme":
                    Theme = value;
                    break;
                case "scale":
                    Scale = value;
                    break;
                case "bling":
                    Style.Bling = ParseBool(value, Style.Bling);
                    break;
                case "rainbow_borders":
                    Style.RainbowBorders = ParseBool(value, Style.RainbowBorders);
                    break;
                case "button_style":
                    Style.ButtonStyle = ParseButtonStyle(value, Style.ButtonStyle);
                    break;
                case "border_effect":
                    Style.BorderEffect = ParseBorderEffect(value, Style.BorderEffect);
                    break;
                case "effect_speed":
                    Style.EffectSpeed = Math.Clamp(ParseInt(value, Style.EffectSpeed), 1, 4);
                    break;
                case "effect_strength":
                    Style.EffectStrength = Math.Clamp(ParseInt(value, Style.EffectStrength), 1, 4);
                    break;
                case "border_thickness":
                    Style.BorderThickness = Math.Clamp(ParseInt(value, Style.BorderThickness), 1, 4);
                    break;
            }
            return;
        }

        if (string.Equals(section, "ui.layout", StringComparison.OrdinalIgnoreCase))
        {
            if (string.Equals(key, "root", StringComparison.OrdinalIgnoreCase))
            {
                Layout.Root = value;
            }
            return;
        }

        if (string.Equals(section, "audio", StringComparison.OrdinalIgnoreCase))
        {
            if (string.Equals(key, "volume", StringComparison.OrdinalIgnoreCase))
            {
                Audio.Volume = Math.Clamp(ParseInt(value, Audio.Volume), 0, 100);
            }
            return;
        }

        if (string.Equals(section, "saturn", StringComparison.OrdinalIgnoreCase))
        {
            if (string.Equals(key, "last_disc", StringComparison.OrdinalIgnoreCase))
            {
                Saturn.LastDisc = value;
            }
            return;
        }

        if (string.Equals(section, "input", StringComparison.OrdinalIgnoreCase))
        {
            Input.Bindings[key.Trim().ToLowerInvariant()] = value.Trim();
            return;
        }

        if (string.Equals(section, "controller", StringComparison.OrdinalIgnoreCase))
        {
            Input.ControllerBindings[key.Trim().ToLowerInvariant()] = value.Trim();
            return;
        }

        const string inputPrefix = "input.";
        if (section.StartsWith(inputPrefix, StringComparison.OrdinalIgnoreCase))
        {
            string profileName = section[inputPrefix.Length..].Trim().ToLowerInvariant();
            if (profileName.Length == 0)
            {
                return;
            }
            CoreInput(profileName).Bindings[key.Trim().ToLowerInvariant()] = value.Trim();
            return;
        }

        const string controllerPrefix = "controller.";
        if (section.StartsWith(controllerPrefix, StringComparison.OrdinalIgnoreCase))
        {
            string profileName = section[controllerPrefix.Length..].Trim().ToLowerInvariant();
            if (profileName.Length == 0)
            {
                return;
            }
            CoreInput(profileName).ControllerBindings[key.Trim().ToLowerInvariant()] = value.Trim();
            return;
        }

        if (string.Equals(section, "external_core", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(section, "external_core2", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(section, "external_core3", StringComparison.OrdinalIgnoreCase))
        {
            UiExternalCoreConfig externalCore = section.ToLowerInvariant() switch
            {
                "external_core2" => ExternalCore2,
                "external_core3" => ExternalCore3,
                _ => ExternalCore,
            };
            switch (key.ToLowerInvariant())
            {
                case "mode":
                    externalCore.Mode = value;
                    break;
                case "command":
                    externalCore.Command = value;
                    break;
                case "args":
                    externalCore.Args = value;
                    break;
                case "working_directory":
                    externalCore.WorkingDirectory = value;
                    break;
                case "env":
                    externalCore.Env = value;
                    break;
                case "wfex_path":
                    externalCore.WfexPath = value;
                    break;
                case "pointer_driver":
                    externalCore.PointerDriver = ParsePointerDriver(value, externalCore.PointerDriver);
                    break;
                case "socket_path":
                    externalCore.SocketPath = value;
                    break;
                case "max_frame_width":
                    externalCore.MaximumFrameWidth = Math.Clamp(ParseInt(value, externalCore.MaximumFrameWidth), 1, 32_768);
                    break;
                case "max_frame_height":
                    externalCore.MaximumFrameHeight = Math.Clamp(ParseInt(value, externalCore.MaximumFrameHeight), 1, 32_768);
                    break;
                case "max_frame_bytes":
                    externalCore.MaximumFrameBytes = Math.Clamp(ParseInt(value, externalCore.MaximumFrameBytes), 4, 1_073_741_824);
                    break;
            }
            return;
        }

        const string windowPrefix = "ui.windows.";
        if (!section.StartsWith(windowPrefix, StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        string windowKey = section[windowPrefix.Length..];
        UiWindowConfig window = Window(windowKey);
        switch (key.ToLowerInvariant())
        {
            case "open":
                window.Open = bool.TryParse(value, out bool open) && open;
                break;
            case "slot":
                window.Slot = value;
                break;
            case "order":
                window.Order = ParseInt(value, window.Order);
                break;
            case "x":
                window.X = ParseInt(value, window.X);
                break;
            case "y":
                window.Y = ParseInt(value, window.Y);
                break;
            case "width":
                window.Width = ParseInt(value, window.Width);
                break;
            case "height":
                window.Height = ParseInt(value, window.Height);
                break;
        }
    }

    private static UiWindowMode ParseWindowMode(string value, UiWindowMode fallback) => value.Trim().ToLowerInvariant() switch
    {
        "floating" => UiWindowMode.Floating,
        "mixed" => UiWindowMode.Mixed,
        "tiled" => UiWindowMode.Tiled,
        _ => fallback,
    };

    private static string Format(UiWindowMode mode) => mode switch
    {
        UiWindowMode.Floating => "floating",
        UiWindowMode.Mixed => "mixed",
        _ => "tiled",
    };

    private static int ParseInt(string value, int fallback)
    {
        return int.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out int parsed) ? parsed : fallback;
    }

    private static bool ParseBool(string value, bool fallback)
    {
        return bool.TryParse(value, out bool parsed) ? parsed : fallback;
    }

    private static string ParseButtonStyle(string value, string fallback)
    {
        return value.Trim().ToLowerInvariant() switch
        {
            "flat" => "flat",
            "edge" => "edge",
            "loud" => "loud",
            _ => fallback,
        };
    }

    private static string ParseBorderEffect(string value, string fallback)
    {
        return value.Trim().ToLowerInvariant() switch
        {
            "still" => "still",
            "glow" => "glow",
            "flow" => "flow",
            _ => fallback,
        };
    }

    private static string ParsePointerDriver(string value, string fallback)
    {
        return value.Trim().ToLowerInvariant() switch
        {
            "absolute" => "absolute",
            "capture" => "capture",
            "raptor" => "raptor",
            "stormakt_rts" => "stormakt_rts",
            "none" => "none",
            _ => fallback,
        };
    }

    private static string StripComment(string line)
    {
        bool inString = false;
        for (int i = 0; i < line.Length; i++)
        {
            if (line[i] == '"')
            {
                inString = !inString;
            }
            else if (!inString && line[i] == '#')
            {
                return line[..i];
            }
        }
        return line;
    }

    private static string Unquote(string value)
    {
        value = value.Trim();
        return value.Length >= 2 && value[0] == '"' && value[^1] == '"' ? value[1..^1] : value;
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
    }

    private static void WriteWfexLimits(StreamWriter writer, UiExternalCoreConfig config)
    {
        writer.WriteLine($"max_frame_width = {config.MaximumFrameWidth.ToString(CultureInfo.InvariantCulture)}");
        writer.WriteLine($"max_frame_height = {config.MaximumFrameHeight.ToString(CultureInfo.InvariantCulture)}");
        writer.WriteLine($"max_frame_bytes = {config.MaximumFrameBytes.ToString(CultureInfo.InvariantCulture)}");
    }
}

internal sealed class UiWindowConfig
{
    public bool Open { get; set; }
    public string Slot { get; set; } = "floating";
    public int Order { get; set; }
    public int X { get; set; }
    public int Y { get; set; }
    public int Width { get; set; }
    public int Height { get; set; }

    public bool HasRect => Width > 0 && Height > 0;

    public RectI ToRect()
    {
        return new RectI(X, Y, Width, Height);
    }

    public void FromWindow(UiWindowState state)
    {
        Open = state.IsOpen;
        if (state.Rect is RectI rect)
        {
            X = rect.X;
            Y = rect.Y;
            Width = rect.Width;
            Height = rect.Height;
        }
    }
}

internal sealed class UiStyleConfig
{
    public bool Bling { get; set; }
    public bool RainbowBorders { get; set; } = true;
    public string ButtonStyle { get; set; } = "flat";
    public string BorderEffect { get; set; } = "glow";
    public int EffectSpeed { get; set; } = 1;
    public int EffectStrength { get; set; } = 1;
    public int BorderThickness { get; set; } = 1;
}

internal sealed class UiAudioConfig
{
    public int Volume { get; set; } = 80;
}

internal sealed class UiSaturnConfig
{
    public string LastDisc { get; set; } = string.Empty;
}

internal sealed class UiInputConfig
{
    public UiInputConfig(bool withDefaults = true)
    {
        if (!withDefaults)
        {
            return;
        }

        foreach (KeyValuePair<string, string> pair in DefaultBindings)
        {
            Bindings[pair.Key] = pair.Value;
        }
        foreach (KeyValuePair<string, string> pair in DefaultControllerBindings)
        {
            ControllerBindings[pair.Key] = pair.Value;
        }
    }

    public Dictionary<string, string> Bindings { get; } = new(StringComparer.OrdinalIgnoreCase);
    public Dictionary<string, string> ControllerBindings { get; } = new(StringComparer.OrdinalIgnoreCase);

    private static readonly Dictionary<string, string> DefaultBindings = new(StringComparer.OrdinalIgnoreCase)
    {
        ["escape"] = "esc",
        ["up"] = "up",
        ["down"] = "down",
        ["left"] = "left",
        ["right"] = "right",
        ["start"] = "enter",
        ["a"] = "z",
        ["b"] = "x",
        ["c"] = "c",
        ["x"] = "a",
        ["y"] = "s",
        ["z"] = "d",
        ["developer_save"] = "f1",
        ["developer_load"] = "f2",
        ["scale_fit"] = "1",
        ["scale_integer"] = "2",
        ["scale_stretch"] = "3",
        ["theme_next"] = "t",
        ["tile_fullscreen"] = "f11",
        ["shift"] = "leftshift,rightshift",
        ["super"] = "leftmeta,rightmeta",
    };

    private static readonly Dictionary<string, string> DefaultControllerBindings = new(StringComparer.OrdinalIgnoreCase)
    {
        ["escape"] = "guide",
        ["up"] = "dpadup,leftstickup",
        ["down"] = "dpaddown,leftstickdown",
        ["left"] = "dpadleft,leftstickleft",
        ["right"] = "dpadright,leftstickright",
        ["start"] = "start",
        ["a"] = "south",
        ["b"] = "east",
        ["c"] = "rightshoulder,righttriggerbutton",
        ["x"] = "west",
        ["y"] = "north",
        ["z"] = "leftshoulder,lefttriggerbutton",
    };
}

internal sealed class UiTileLayoutConfig
{
    public string Root { get; set; } = string.Empty;
}

internal sealed class UiExternalCoreConfig
{
    public string Mode { get; set; } = "stdio";
    public string Command { get; set; } = string.Empty;
    public string Args { get; set; } = string.Empty;
    public string WorkingDirectory { get; set; } = string.Empty;
    public string Env { get; set; } = string.Empty;
    public string WfexPath { get; set; } = string.Empty;
    public string PointerDriver { get; set; } = "absolute";
    public string SocketPath { get; set; } = string.Empty;
    public int MaximumFrameWidth { get; set; } = WfexLimits.Default.MaximumWidth;
    public int MaximumFrameHeight { get; set; } = WfexLimits.Default.MaximumHeight;
    public int MaximumFrameBytes { get; set; } = WfexLimits.Default.MaximumPayloadBytes;
}
